global:
  scrape_interval: 5s   # A cada 5 segundos

scrape_configs:
  - job_name: 'app-langchain4j'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']   # Se estiver usando Docker
        labels:
          app: 'ia-langchain4j'
